### ISSUE TITLE
Remove uses of deprecated and non-public accumulo apis

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#2443]
Se need to do a scrub of datawave and remove any uses of non-public and deprecated accumulo apis.  Note that for non-public apis, there may be situations where that cannot be done and we can subsequently request that accumulo make something public for us.

## Sub-Issues Progress

- [x] #3163 - Replace org.apache.accumulo.core.classloader.ClassLoaderUtil
- [x] #3176 - Replace Deprecated AbstractEventRecordReader
- [x] #3177 - Replace deprecated setDate(long)
- [x] #3178 - Replace deprecated AdvancedCacheLoader
- [x] #3179 - Replace deprecated KeyFilter
- [x] #3180 - Replace deprecated CacheLoaderTask
- [x] #3181 - Replace deprecated TaskContext
- [x] #3182 - Replace deprecated SingletonStoreConfiguration
- [x] #3184 - Replace deprecated InstanceOperations.getInstanceID()
- [x] #3185 - Replace deprecated TableId.getTableId()
- [x] #3187 - Replace deprecated Integer(int)
- [x] #3292 - Replace deprecated Float, Long, Double, Boolean constructors
- [x] #3293 - Replace deprecated Date(year, month, day) constructor
- [x] #3294 - Replace deprecated Job() constructor in MultiTableRRRangePartitionerTest
- [x] #3298 - Replace deprecated Byte, Character, Short constructors
- [x] #3300 - Replace deprecated Date(String) constructor
- [x] #3313 - Replace Charset.forName("UTF-8") with StandardCharsets.UTF_8
- [x] #3319 - Remove deprecated TabletLocator methods
- [x] #3335 - Fix incorrect WrappedConnector check in ScannerFactory
- [x] #3336 - Replace non-public IterationInterruptedException with class name check
- [x] #3337 - Remove unused SortedMapIterator import from ArrayIterator
- [x] #3339 - Replace ClientContext.getTableId with public API
- [x] #3341 - Replace non-public ScanTimedOutException import
- [x] #3343 - Remove deprecated TabletLocator usage
- [x] #3348 - Replace non-public BadArgumentException with IllegalArgumentException
- [x] #3358 - Replace non-public DateFormatSupplier
- [x] #3374 - Replace non-public ThreadPools
- [x] #3376 - Replace non-public CloneConfigurationImpl in test

- [ ] #3164 - Replace org.apache.accumulo.core.clientImpl.ClientConfConverter
- [ ] #3165 - Replace org.apache.accumulo.core.clientImpl.ClientContext
- [ ] #3166 - Replace org.apache.accumulo.core.clientImpl.ClientInfo
- [ ] #3167 - Replace org.apache.accumulo.core.clientImpl.ClientInfoImpl
- [ ] #3168 - Replace org.apache.accumulo.core.clientImpl.Credentials
- [ ] #3186 - Replace deprecated Object.finalize()
- [x] #3311 - Replace deprecated Class.newInstance()
- [ ] #3317 - Replace non-public TabletClosedException and ScanTimedOutException
- [ ] #3321 - Replace non-public SortedMapIterator with DataWave utility
- [x] #3323 - Remove non-public OutputConfigurator usage
- [x] #3334 - Remove non-public API usage from ScannerBaseDelegate
- [ ] #3349 - Replace non-public ByteBufferUtil and TextUtil
- [ ] #3350 - Replace non-public MapCounter with DataWave utility
- [ ] #3352 - Replace non-public MetadataTable.NAME
- [ ] #3353 - Replace non-public RootTable.NAME
- [ ] #3354 - Replace non-public ReplicationTable.NAME
- [ ] #3355 - Replace non-public TableNameUtil.qualify()
- [ ] #3357 - Replace non-public Validators
- [ ] #3365 - Tangled: Replace deprecated Infinispan Cache APIs
- [ ] #3366 - Tangled: Replace non-public clientImpl APIs
- [ ] #3367 - Tangled: Replace non-public table constants
- [ ] #3372 - Replace non-public KeyExtent and TabletIdImpl
- [ ] #3373 - Replace non-public SecurityErrorCode
- [ ] #3375 - Replace non-public ConfigurationImpl in tests
- [ ] #3377 - Regression: non-public Threads still used in BulkInputFormat
- [ ] #3393 - Replace non-public IterationInterruptedException in next/ package

**Comment by lbschanno** [comment]
- [ ] Task list test

**Comment by lbschanno** [comment]
List of PRs created for this ticket. Subject to update.
- #2488 
- #2490
- #2491 
- #2492 
- #2496 
- #2497 
- #2498 
- #2499 
- #2500 
- #2501 
- #2502 
- #2550 
- #2520
- #2525 
- #2526 
- #2527 
- #2528 
- #2534 
- #2539

**Comment by lbschanno** [comment]
Breaking this out into multiple sub-tickets since we now have that feature available.

**Comment by lbschanno** [comment]
Currently there are 90 distinct classes from Accumulo being used in Datawave that are not part of their public API. These can be listed via the following command while at the root of the datawave folder:
```
find . -type f -name '*.java' | xargs grep -P -h 'import\s+org\.apache\.accumulo\.(?!(core\.(client|data|iterators|security)|minicluster|hadoop)\.).*' | sort | uniq | sed "s/^[^ ]* //" | sed "s/;//"
```

```
org.apache.accumulo.core.classloader.ClassLoaderUtil
org.apache.accumulo.core.clientImpl.ClientConfConverter
org.apache.accumulo.core.clientImpl.ClientContext
org.apache.accumulo.core.clientImpl.ClientInfo
org.apache.accumulo.core.clientImpl.ClientInfoImpl
org.apache.accumulo.core.clientImpl.Credentials
org.apache.accumulo.core.clientImpl.Namespace
org.apache.accumulo.core.clientImpl.NamespaceOperationsHelper
org.apache.accumulo.core.clientImpl.ScannerOptions
org.apache.accumulo.core.clientImpl.TableOperationsHelper
org.apache.accumulo.core.clientImpl.TabletLocator
org.apache.accumulo.core.clientImpl.ThriftScanner.ScanTimedOutException
org.apache.accumulo.core.clientImpl.thrift.SecurityErrorCode
org.apache.accumulo.core.conf.AccumuloConfiguration
org.apache.accumulo.core.conf.ClientProperty
org.apache.accumulo.core.conf.ConfigurationCopy
org.apache.accumulo.core.conf.DefaultConfiguration
org.apache.accumulo.core.conf.Property
org.apache.accumulo.core.conf.SiteConfiguration
org.apache.accumulo.core.crypto.CryptoFactoryLoader
org.apache.accumulo.core.dataImpl.KeyExtent
org.apache.accumulo.core.dataImpl.TabletIdImpl
org.apache.accumulo.core.dataImpl.thrift.IterInfo
org.apache.accumulo.core.fate.zookeeper.ZooCache
org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile
org.apache.accumulo.core.file.blockfile.impl.CachableBlockFile.Reader
org.apache.accumulo.core.file.FileOperations
org.apache.accumulo.core.file.FileSKVIterator
org.apache.accumulo.core.file.FileSKVWriter
org.apache.accumulo.core.file.keyfunctor.KeyFunctor
org.apache.accumulo.core.file.rfile.RFile
org.apache.accumulo.core.file.rfile.RFileOperations
org.apache.accumulo.core.iteratorsImpl.conf.ColumnSet
org.apache.accumulo.core.iteratorsImpl.conf.ColumnToClassMapping
org.apache.accumulo.core.iteratorsImpl.IteratorBuilder
org.apache.accumulo.core.iteratorsImpl.IteratorConfigUtil
org.apache.accumulo.core.iteratorsImpl.system.ColumnFamilySkippingIterator
org.apache.accumulo.core.iteratorsImpl.system.ColumnQualifierFilter
org.apache.accumulo.core.iteratorsImpl.system.DeletingIterator
org.apache.accumulo.core.iteratorsImpl.system.InterruptibleIterator
org.apache.accumulo.core.iteratorsImpl.system.IterationInterruptedException
org.apache.accumulo.core.iteratorsImpl.system.MultiIterator
org.apache.accumulo.core.iteratorsImpl.system.SortedMapIterator
org.apache.accumulo.core.iteratorsImpl.system.VisibilityFilter
org.apache.accumulo.core.manager.balancer.AssignmentParamsImpl
org.apache.accumulo.core.manager.balancer.BalanceParamsImpl
org.apache.accumulo.core.manager.balancer.TabletServerIdImpl
org.apache.accumulo.core.manager.balancer.TServerStatusImpl
org.apache.accumulo.core.manager.state.tables.TableState
org.apache.accumulo.core.manager.thrift.ManagerClientService
org.apache.accumulo.core.manager.thrift.ManagerMonitorInfo
org.apache.accumulo.core.master.thrift.TableInfo
org.apache.accumulo.core.master.thrift.TabletServerStatus
org.apache.accumulo.core.metadata.MetadataServicer
org.apache.accumulo.core.metadata.MetadataTable
org.apache.accumulo.core.metadata.RootTable
org.apache.accumulo.core.metadata.schema.MetadataSchema
org.apache.accumulo.core.metadata.TServerInstance
org.apache.accumulo.core.replication.ReplicationTable
org.apache.accumulo.core.rpc.clients.ThriftClientTypes
org.apache.accumulo.core.rpc.ThriftUtil
org.apache.accumulo.core.singletons.SingletonManager
org.apache.accumulo.core.singletons.SingletonReservation
org.apache.accumulo.core.spi.balancer.BalancerEnvironment
org.apache.accumulo.core.spi.balancer.data.TabletMigration
org.apache.accumulo.core.spi.balancer.data.TabletServerId
org.apache.accumulo.core.spi.balancer.data.TabletStatistics
org.apache.accumulo.core.spi.balancer.data.TServerStatus
org.apache.accumulo.core.spi.balancer.GroupBalancer
org.apache.accumulo.core.spi.balancer.TabletBalancer
org.apache.accumulo.core.spi.common.ServiceEnvironment
org.apache.accumulo.core.spi.common.ServiceEnvironment.Configuration
org.apache.accumulo.core.spi.crypto.CryptoEnvironment
org.apache.accumulo.core.spi.crypto.CryptoService
org.apache.accumulo.core.spi.file.rfile.compression.NoCompression
org.apache.accumulo.core.spi.fs.RandomVolumeChooser
org.apache.accumulo.core.spi.fs.VolumeChooserEnvironment
org.apache.accumulo.core.util.ByteBufferUtil
org.apache.accumulo.core.util.ConfigurationImpl
org.apache.accumulo.core.util.format.DateFormatSupplier
org.apache.accumulo.core.util.MapCounter
org.apache.accumulo.core.util.Pair
org.apache.accumulo.core.util.tables.TableNameUtil
org.apache.accumulo.core.util.TextUtil
org.apache.accumulo.core.util.threads.ThreadPools
org.apache.accumulo.core.util.threads.Threads
org.apache.accumulo.core.util.Validators
org.apache.accumulo.hadoopImpl.mapreduce.AccumuloRecordWriter
org.apache.accumulo.hadoopImpl.mapreduce.lib.OutputConfigurator
org.apache.accumulo.tserver.tablet.TabletClosedException
```

**Comment by SethSmucker** [comment]
Additional PRs created:
- #3312 - Replace deprecated Class.newInstance() (fixes #3311)
- #3314 - Replace Charset.forName("UTF-8") with StandardCharsets.UTF_8 (fixes #3313)

**Comment by SethSmucker** [comment]
Additional PR created:
- #3315 - Replace non-public ClassLoaderUtil with standard Java reflection (fixes #3163)

**Comment by SethSmucker** [comment]
Additional PR created:
- #3345 - Replace InMemoryInstance with InMemoryAccumulo (fixes #2597)

Note: This PR depends on #3253 being merged first.
